### ISSUE TITLE
cannot upgrade due to dependency breaking.

### ISSUE THREAD

**Issue by 96jaco96** [zzag/plasma5-wallpapers-dynamic#131]
If i try to update my Arch system with sudo pacman -Syu i get: 

installing plasma-framework5 (5.111.0-1) breaks dependency 'plasma-framework' required by plasma5-wallpapers-dynamic

**Comment by zzag** [comment]
Should be fixed. Thanks for letting me know.

**Comment by OkyDooky** [comment]
Fixed when/how? I just came here after experiencing the same thing. I was about to post on my distro's forums, but then I thought to search the web for the plasma5-wallpapers-dynamic part, remembering that I installed something like that a good while back.
Do I need to wait for another formal release? Or could I just remove it, upgrade system, and then reinstall it?

I'd recommend keeping this open until the fix is pushed through and verified by the affected users.
