### ISSUE TITLE
I'm encounter hurge lag when loading the wallpaper.

### ISSUE THREAD

**Issue by qqpp4130** [zzag/plasma5-wallpapers-dynamic#44]
For newest version, i assume the heic is a compressed package of all meta information and images, and that seems to be a problem when using 4K resolution images .. it's too slow.
During previous version where all picture is sepreted, that makes my hardware affordable this level of resource, but now I found my self on loading the wallpaper.heic tooks more than 15 seconds. Can some what improve on this part? Probably still keep the previous format as well??

**Comment by zzag** [comment]
Sorry for making things more inconvenient on your side.

In general, how fast a wallpaper is going to be loaded depends on the heic file. Some 4K wallpapers are loaded super fast, while some other are not. I suggest to report this issue to libheif developers [1]. I'm not familiar with libheif internals well, but my greatest fear is that libheif doesn't split workload between threads. Note that you would have to provide a heic file.

During normal day operation, this issue shouldn't be noticeable because all image loading is happening asynchronously in another thread.

> Can some what improve on this part? Probably still keep the previous format as well??

Given that I'm the only active developer, I don't want to maintain several wallpaper formats. Frankly, I don't know how this issue can be addressed (maybe use a cache?). Although, first, I would like to know if it's a libheif issue after all.

[1] https://github.com/strukturag/libheif/issues

**Comment by qqpp4130** [comment]
if that is the case, then this is rather complacated. I have provided the heif, which is the mojave dynamic wallpaper. There is one thing bring up to me, the encoding process using the packing program you provided in the package, tooks more than 4 minuits. I'm not familer with libheif, but i may have too many images together... 
The size of the wallpaper is 99.4 MB, B aware. I attatched the google driv link..

**Comment by Teeffelen** [comment]
I scaled my Apple 4K wallpapers (from Catalina) to 1920x1309, since my laptop is only 1920x1080, which helped a lot with loading times (was around 15sec, now around 2sec).

**Comment by zzag** [comment]
Commit f648cb831 should cut the loading time in half, other than that, I don't see what I can do about the performance issues.

**Comment by qqpp4130** [comment]
Improvement is Significant! Thanks XD
