### ISSUE TITLE
You need at least Qt 5.14 to preserve color profiles

### ISSUE THREAD

**Issue by fahadlk** [zzag/plasma5-wallpapers-dynamic#59]
When I try to make a wallpaper, I get error in topic four times, probably cause I have 4 images. I am using kubuntu with qt version 5.12.8. What can I do?
![image](https://user-images.githubusercontent.com/47036399/89177919-e6663700-d5a5-11ea-9dca-01f1367ee5eb.png)

**Comment by zzag** [comment]
Those warnings say that color profiles from source images can't be saved since your system has a slightly old version of Qt. If you don't really care about color profiles, you can ignore those warning messages. Alternatively, you could explicitly discard embedded color profiles by passing `--discard-color-profile` to kdynamicwallpaperbuilder.

**Comment by zzag** [comment]
If you do want to preserve embedded color profiles, you need to install Qt 5.14.

**Comment by zzag** [comment]
... and re-compile plasma5-wallpapers-dynamic afterward.

**Comment by fahadlk** [comment]
thanks, it worked.
