### ISSUE TITLE
No EXIF time data.

### ISSUE THREAD

**Issue by phoenix277yt** [zzag/plasma5-wallpapers-dynamic#72]
Is it necessary to have the EXIF time data in the image because I would like to set the wallpapers from in-game screenshots but they don't have the EXIF time data. I've even provided the time data in the .json file while the sun position is set to auto (*).

![image](https://user-images.githubusercontent.com/73348506/107759618-93d4b700-6d4e-11eb-9ec2-4f58fbfe5f4c.png)
My .json file and folder structure

![image](https://user-images.githubusercontent.com/73348506/107759691-abac3b00-6d4e-11eb-80fb-c94c6a19964f.png)
Kwallpaperbuilder output, I know it says to do that but is it really necessary?
@zzag

**Comment by zzag** [comment]
If the images have no EXIF metadata and you don't the position of the Sun, just omit `SolarAzimuth` and `SolarElevation`.

**Comment by zzag** [comment]
>  Kwallpaperbuilder output, I know it says to do that but is it really necessary?

It depends on if you need your dynamic wallpaper include solar metadata. In order to calculate the position of the Sun, both the location and date + time are required. Alternatively, you could compute the position of the Sun on your own, but it's not as convenient as calculating SolarAzimuth and SolarElevation auto-magically based on EXIF metadata.
