### ISSUE TITLE
KDE plugin manager: An Error Occurred

### ISSUE THREAD

**Issue by dogunbound** [zzag/plasma5-wallpapers-dynamic#84]
The installation of /tmp/AILHIK-plasma5-wallpapers-dynamic-2.6.tar.gz failed, as the downloaded package does not contain any useful meta information, which means it is not a valid KPackage.

Can't install it through the kde store which I assume is where you plan it to be installed from.

**Comment by zzag** [comment]
2.6 is quite old. If you use Arch, you can install this plugin from AUR (I maintain the package). If you use Fedora or Ubuntu, you can install the plugin without building it from source code, see README.md. Otherwise, the only option is to build it yourself from source code, again see README.md file.
